name: Node CI

on:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 15.0.1
        cache: npm
    - name: Install dependencies
      run: npm install
    - name: ESLint
      run: npm run lint
    - name: Prettier
      run: |
        npm install --save-dev --save-exact prettier
        npm run prettier --write 
    - name: Test
      run: CI=true npm run test
    - name: Build
      run: npm run build
